baseURL = "http://zy.io/"
languageCode = "en-gb"
title = "Sam Norbury"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Sam Norbury"
    description = "DevOps consultant. Likes Ansible and long walks on the beach."
    githubUsername = "zyio"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["ruby", "bash"]
    copyright = "&copy; All rights reserved."

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/blog/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:sam@zy.io"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://www.instagram.com/sam.norbury/"
    name = "instagram"
    weight = 2

[[menu.icon]]
    url = "https://github.com/zyio/"
    name = "github"
    weight = 3

[[menu.icon]]
    url = "https://keybase.io/zyio"
    name = "key"
    weight = 4

[[menu.icon]]
    url = "https://www.linkedin.com/in/sam-norbury/"
    name = "linkedin"
    weight = 5
